function [MOVINGREG] = registerp(MOVING,FIXED)
%registerImages  Register grayscale images using auto-generated code from Registration Estimator app.
%  [MOVINGREG] = registerImages(MOVING,FIXED) Register grayscale images
%  MOVING and FIXED using auto-generated code from the Registration
%  Estimator app. The values for all registration parameters were set
%  interactively in the app and result in the registered image stored in the
%  structure array MOVINGREG.

% Auto-generated by registrationEstimator app on 20-Aug-2020
%-----------------------------------------------------------


% Convert RGB images to grayscale
MMOVING = MOVING;
FIXED = rgb2gray(FIXED);
MOVING = rgb2gray(MOVING);

% Default spatial referencing objects
fixedRefObj = imref2d(size(FIXED));
movingRefObj = imref2d(size(MOVING));

% Phase correlation
tform = imregcorr(MOVING,movingRefObj,FIXED,fixedRefObj,'transformtype','translation','Window',true);
MOVINGREG.Transformation = tform;
MOVINGREG.RegisteredImage = imwarp(MMOVING, movingRefObj, tform, 'OutputView', fixedRefObj, 'SmoothEdges', true);

% Store spatial referencing object
MOVINGREG.SpatialRefObj = fixedRefObj;

end

